### ISSUE TITLE
trouble with 'loadlambda' for spectral line images

### ISSUE THREAD

**Issue by seanandrews** [dullemond/radmc3d-2.0#12]
I'd like to specify the exact wavelengths to calculate images of a spectral line, as specified with 'camera_wavelength_micron.inp' and the 'loadlambda' flag.  But this doesn't seem to work.  The command I'm issuing is:

`radmc3d image incl 40 posang 130 npix 256 sizeau 1000 iline 2 loadlambda setthreads 6`

with the following lines in 'camera_wavelength_micron.inp':

4
1.300401486960214470e+03
1.300403655796441399e+03
1.300405824639902676e+03
1.300407993490598756e+03

(This is intended to be the CO 2-1 line, using the LAMDA database file.)  When I run this, it always only computes an image for a single wavelength, 1300.4036557964414 microns.  Notably, this is the 2nd of the values above.  

I do not seem to have any trouble when I instead swap out `loadlambda` for, e.g., `widthkms 4 linenlam 10` or something (the output cube in that case looks perfectly fine).  But, manipulating things to work that way will undoubtedly confuse me later (and other users of my setup), and it's important to compute at exact, specific wavelengths.  Any idea if there's something I'm doing wrong here?  (I hope it's simple!)

**Comment by dullemond** [comment]
Hi Sean,
If you set the `iline 2` option, RADMC-3D thinks you want to center your frequencies around that line. It then ignores the `loadlambda`. So just remove the `iline 2` as you don't need it anyway. 
But I see that this is confusing, so I will add a check that mutually excludes the `iline`, `ispec`, `vkms` options against `loadlambda`.
Thanks for pointing out the problem!
Best wishes,
Kees

**Comment by seanandrews** [comment]
Hi Kees,
Excellent!  Indeed, this solves the issue.  Thanks for the very prompt fix and reply!  (I suspected it was a misunderstanding on my part...)
cheers,
Sean

**Comment by dullemond** [comment]
I have now added an error message if two methods for setting the wavelengths are used simultaneously. So this type of accident cannot occur anymore.
