### ISSUE TITLE
ld: library not found for -lSystem

### ISSUE THREAD

**Issue by Loria11** [dullemond/radmc3d-2.0#2]
I am on the new M1 Mac Book Pro and am trying to install and when writing `make` I get the following error. Any help on how to fix this? 

> gfortran -O2 -fopenmp  main.o rtglobal_module.o montecarlo_module.o dust_module.o quantum_module.o mathroutines_module.o ioput_module.o stars_module.o amr_module.o amrray_module.o constants_module.o camera_module.o lines_module.o namelist_module.o userdef_module.o gascontinuum_module.o polarization_module.o sources_module.o  -o radmc3d 
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make: *** [radmc3d] Error 1

**Comment by l-sz** [comment]
The main issue is that the stable releases of the gcc/gfortran compiler do not support the M1 ARM architecture yet. How do you install the fortran compiler that would be used to compile radmc-3d?

There is ongoing work to provide gcc support on this architecture, but it is not yet available on official channels. There is a [private repository](https://github.com/iains/gcc-darwin-arm64) and [executable builds](https://github.com/fxcoudert/gfortran-for-macOS/releases) based on it, but i would not recommend installing them.

Alternatively, the Rosetta 2 compatibility layer should make it possible to run the x86 complier and/or x86 radmc3d binary on your machine. You could create a "copy" of the terminal application, then in the "Get info" panel select "Open using Rosetta". Using this terminal, you may now need to install an x86 compiler. From then on try compiling it as on x86 platform.

Note that giving advice on this without having the actual M1 based hardware is difficult. Please report back what you find, as it may be useful for others.

**Comment by Loria11** [comment]
I was able to get it up and running using exactly that. I had to use Homebrew to install gcc/gfortran and then use the x86 compiler `-x86_64` before everything, I aliased that into "intel" since that is uncomfortable to write. No need to "copy" the terminal app, just write that before anything you do that you want in x86. I had to do the same when installing Python. Python on these new machines is running through the ARM architecture. So basically anything you want to run must have the `-x86_64` in front. After that everything seems to work fine in radome-3d, haven't had a problem yet. 

Everything runs smooth and fast.

**Comment by dullemond** [comment]
Thanks guys! In principle RADMC-3D is written in standard Fortran, so it should also compile with non-GNU compilers. Of course this could sometimes lead to small tweaks to be necessary. If you run into such issues, let me know.
Cheers,
Kees
