### ISSUE TITLE
A few typos in manual

### ISSUE THREAD

**Issue by mr91i** [dullemond/radmc3d-2.0#8]
I found a few typos in RADMC-3D manual and so report them. 

- page 150: "camera_min_dr" should be "camera_min_**drr**".
- page 150: option "camera_diagnostics_subpix" in radmc3d.inp cannot be used. I could not find a line that reads such an option at `subroutine read_radmcinp_file()` in `radmc3d-2.0/src/main.f90`. So another option name might be used, or the option in radmc3d.inp might not be implemented originally.

(By the way, I created an issue (now closed) by mistake, so please delete it.)

**Comment by dullemond** [comment]
Thanks, Shoji. 
Sorry it tool so long. Now fixed.
Cheers,
Kees
